### PR TITLE
remove debug print()

### PR DESCRIPTION
**Pull request by phsiao**
Found a print() in object_factory() that was left behind from earlier.

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks!

**Comment by phsiao** [comment]
@hjacobs thanks for merging, any chance you can make a 0.23 release soon so we can avoid the noise in the stdout?  Thanks.

**Comment by hjacobs** [comment]
done: https://github.com/hjacobs/pykube/releases/tag/0.23

**Comment by phsiao** [comment]
Thank you!

**Pull request merged**
