### PR TITLE
Fix Windows paths by using posixpath for URL building 

### PR DESCRIPTION
**Pull request by jbw**
This PR fixes a bug in Windows where api_kwargs builds an invalid URL.

#57

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks, but this also removes the `normpath` call which IMHO should be added back.

**Comment by jbw** [comment]
> `normpath`

@hjacobs  thanks for picking this project up by the way.

The problem with normpath is is it meant for file system interactivity and will handle separators depending on the OS. Using normpath here will introduce the same problem.

I guess the larger problem here is that URLs are being created with OS path modules.  I'm not close with the code base so, what benefit does `normpath` have in this part of code for constructing URLs?

**Comment by hjacobs** [comment]
I just tested it --- it won't work without normpath! I'm now adding a function to do the URL join without filesystem/posix functions.

**Comment by hjacobs** [comment]
I implemented a new utility function to stop using filesystem path functions: #59

**Comment by jbw** [comment]
> I implemented a new utility function to stop using filesystem path functions: #59

Thanks! It is a shame this won't solve my problem in the original pykube repo which i currently depend on!

**Comment by hjacobs** [comment]
@jbw what makes you still depend on the original pykube repo (https://github.com/kelproject/pykube)?

**Comment by jbw** [comment]
@hjacobs i'm using Luigi (https://github.com/spotify/luigi) and it's Kubernetes integration (https://github.com/spotify/luigi/blob/master/luigi/contrib/kubernetes.py). It should be the case i can simply substitute pykube for pykube-ng (assuming the api is the same). I'm going to test this out and see.

**Pull request closed without merging**
